[2025-03-24 22:25:09] [ERROR] [django] Usuario() got unexpected keyword arguments: 'senha'
Traceback (most recent call last):
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/ninja/operation.py", line 133, in run
    result = self.view_func(request, **values)
  File "/home/vidal/programas_python/lojex/apps/usuarios/routers.py", line 22, in criar_usuario
    usuario_obj = Usuario.objects.create(**usuario.dict())
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 677, in create
    obj = self.model(**kwargs)
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: Usuario() got unexpected keyword arguments: 'senha'
[2025-03-24 22:25:09] [ERROR] [django.request] Internal Server Error: /api/usuarios/
[2025-03-24 22:25:09] [ERROR] [django.server] "POST /api/usuarios/ HTTP/1.1" 500 1008
[2025-03-24 22:26:49] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-24 22:26:50] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:28:18] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:28:19] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:28:24] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-24 22:28:24] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3022
[2025-03-24 22:28:58] [INFO] [django.server] "POST /api/usuarios/ HTTP/1.1" 200 230
[2025-03-24 22:29:25] [INFO] [usuarios] Usuário brunaluiza@gmail.com logado com sucesso.
[2025-03-24 22:29:25] [ERROR] [django.request] Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vidal/programas_python/lojex/apps/usuarios/views.py", line 34, in login_user
    return redirect("pagina_inicial")  # Atualize para a página inicial correta
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'pagina_inicial' not found. 'pagina_inicial' is not a valid view function or pattern name.
[2025-03-24 22:29:25] [ERROR] [django.server] "POST /login/ HTTP/1.1" 500 92335
[2025-03-24 22:29:47] [INFO] [django.server] "GET /login/ HTTP/1.1" 200 2857
[2025-03-24 22:29:52] [WARNING] [usuarios] Tentativa de login falha para brunaluiza@gmail.com. Credenciais incorretas.
[2025-03-24 22:29:52] [INFO] [django.server] "POST /login/ HTTP/1.1" 200 3024
[2025-03-24 22:29:52] [INFO] [django.server] "GET /static/assets/images/logos/logo.svg HTTP/1.1" 304 0
[2025-03-24 22:30:08] [ERROR] [django] UNIQUE constraint failed: usuarios_usuario.email
Traceback (most recent call last):
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: usuarios_usuario.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/ninja/operation.py", line 133, in run
    result = self.view_func(request, **values)
  File "/home/vidal/programas_python/lojex/apps/usuarios/routers.py", line 24, in criar_usuario
    usuario_obj = Usuario.objects.create_user(senha=senha, **data)
  File "/home/vidal/programas_python/lojex/apps/usuarios/models.py", line 28, in create_user
    usuario.save(using=self._db)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/contrib/auth/base_user.py", line 62, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 892, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 998, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1161, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1202, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: usuarios_usuario.email
[2025-03-24 22:30:08] [ERROR] [django.request] Internal Server Error: /api/usuarios/
[2025-03-24 22:30:08] [ERROR] [django.server] "POST /api/usuarios/ HTTP/1.1" 500 4764
[2025-03-24 22:31:39] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:31:39] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:31:44] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:31:44] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:31:49] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:31:49] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:31:57] [ERROR] [django] name 'HttpError' is not defined
Traceback (most recent call last):
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/ninja/operation.py", line 133, in run
    result = self.view_func(request, **values)
  File "/home/vidal/programas_python/lojex/apps/usuarios/routers.py", line 24, in criar_usuario
    raise HttpError(400, "Usuário com este e-mail já existe")
          ^^^^^^^^^
NameError: name 'HttpError' is not defined. Did you mean: 'TypeError'?
[2025-03-24 22:31:57] [ERROR] [django.request] Internal Server Error: /api/usuarios/
[2025-03-24 22:31:57] [ERROR] [django.server] "POST /api/usuarios/ HTTP/1.1" 500 449
[2025-03-24 22:32:00] [ERROR] [django] name 'HttpError' is not defined
Traceback (most recent call last):
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/ninja/operation.py", line 133, in run
    result = self.view_func(request, **values)
  File "/home/vidal/programas_python/lojex/apps/usuarios/routers.py", line 24, in criar_usuario
    raise HttpError(400, "Usuário com este e-mail já existe")
          ^^^^^^^^^
NameError: name 'HttpError' is not defined. Did you mean: 'TypeError'?
[2025-03-24 22:32:00] [ERROR] [django.request] Internal Server Error: /api/usuarios/
[2025-03-24 22:32:00] [ERROR] [django.server] "POST /api/usuarios/ HTTP/1.1" 500 449
[2025-03-24 22:32:01] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-24 22:32:01] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3022
[2025-03-24 22:32:17] [INFO] [django.server] "GET /api/usuarios/ HTTP/1.1" 200 1566
[2025-03-24 22:32:36] [ERROR] [django] name 'HttpError' is not defined
Traceback (most recent call last):
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/ninja/operation.py", line 133, in run
    result = self.view_func(request, **values)
  File "/home/vidal/programas_python/lojex/apps/usuarios/routers.py", line 24, in criar_usuario
    raise HttpError(400, "Usuário com este e-mail já existe")
          ^^^^^^^^^
NameError: name 'HttpError' is not defined. Did you mean: 'TypeError'?
[2025-03-24 22:32:36] [ERROR] [django.request] Internal Server Error: /api/usuarios/
[2025-03-24 22:32:36] [ERROR] [django.server] "POST /api/usuarios/ HTTP/1.1" 500 449
[2025-03-24 22:33:17] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:33:18] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:33:20] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:33:21] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:33:24] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:33:26] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:34:38] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:34:39] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:34:43] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:34:43] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:34:47] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:34:47] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:34:54] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:34:54] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:34:56] [INFO] [django.server] "GET /api/usuarios/ HTTP/1.1" 200 1566
[2025-03-24 22:35:07] [ERROR] [django] name 'HttpError' is not defined
Traceback (most recent call last):
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/ninja/operation.py", line 133, in run
    result = self.view_func(request, **values)
  File "/home/vidal/programas_python/lojex/apps/usuarios/routers.py", line 24, in criar_usuario
    raise HttpError(400, "Usuário com este e-mail já existe")
          ^^^^^^^^^
NameError: name 'HttpError' is not defined. Did you mean: 'TypeError'?
[2025-03-24 22:35:07] [ERROR] [django.request] Internal Server Error: /api/usuarios/
[2025-03-24 22:35:07] [ERROR] [django.server] "POST /api/usuarios/ HTTP/1.1" 500 449
[2025-03-24 22:35:09] [ERROR] [django] name 'HttpError' is not defined
Traceback (most recent call last):
  File "/home/vidal/programas_python/lojex/.venv/lib/python3.13/site-packages/ninja/operation.py", line 133, in run
    result = self.view_func(request, **values)
  File "/home/vidal/programas_python/lojex/apps/usuarios/routers.py", line 24, in criar_usuario
    raise HttpError(400, "Usuário com este e-mail já existe")
          ^^^^^^^^^
NameError: name 'HttpError' is not defined. Did you mean: 'TypeError'?
[2025-03-24 22:35:09] [ERROR] [django.request] Internal Server Error: /api/usuarios/
[2025-03-24 22:35:09] [ERROR] [django.server] "POST /api/usuarios/ HTTP/1.1" 500 449
[2025-03-24 22:35:28] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:35:30] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:35:38] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:35:39] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:36:25] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:36:26] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:36:32] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:36:39] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:36:40] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:36:46] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:36:46] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:37:39] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:37:40] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:37:50] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:37:51] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:38:11] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:38:11] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:38:15] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:38:15] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:38:20] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-24 22:38:20] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
[2025-03-24 22:38:24] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-24 22:38:24] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
[2025-03-24 22:38:25] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-24 22:38:25] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
[2025-03-24 22:38:49] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-24 22:38:49] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-24 22:39:48] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-24 22:39:48] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
[2025-03-24 22:41:08] [WARNING] [django.request] Not Found: /api/usuarios/115
[2025-03-24 22:41:08] [WARNING] [django.server] "GET /api/usuarios/115 HTTP/1.1" 404 60
[2025-03-24 22:46:15] [WARNING] [usuarios] Tentativa de login falha para brunaluiza@gmail.com. Credenciais incorretas.
[2025-03-24 22:46:15] [INFO] [django.server] "POST /login/ HTTP/1.1" 200 3024
[2025-03-24 22:46:15] [INFO] [django.server] "GET /static/assets/images/logos/logo.svg HTTP/1.1" 304 0
[2025-03-25 06:33:17] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:33:24] [WARNING] [django.request] Not Found: /
[2025-03-25 06:33:24] [WARNING] [django.server] "GET / HTTP/1.1" 404 5085
[2025-03-25 06:33:25] [WARNING] [django.request] Not Found: /
[2025-03-25 06:33:25] [WARNING] [django.server] "GET / HTTP/1.1" 404 5085
[2025-03-25 06:33:27] [WARNING] [django.request] Not Found: /favicon.ico
[2025-03-25 06:33:27] [WARNING] [django.server] "GET /favicon.ico HTTP/1.1" 404 5136
[2025-03-25 06:33:32] [INFO] [django.server] "GET /api/usuarios/ HTTP/1.1" 200 1566
[2025-03-25 06:33:46] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:33:47] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:33:53] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:33:53] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:33:56] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:33:57] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:34:01] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:34:02] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:34:05] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:34:06] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:34:11] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:34:12] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:34:18] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:34:19] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:34:51] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:34:51] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:34:57] [WARNING] [django.request] Not Found: /api/docs/
[2025-03-25 06:34:57] [WARNING] [django.server] "GET /api/docs/ HTTP/1.1" 404 7171
[2025-03-25 06:35:27] [WARNING] [django.request] Not Found: /api/rdoc/
[2025-03-25 06:35:27] [WARNING] [django.server] "GET /api/rdoc/ HTTP/1.1" 404 7171
[2025-03-25 06:35:33] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:35:34] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:35:40] [WARNING] [django.request] Not Found: /api/docs/
[2025-03-25 06:35:40] [WARNING] [django.server] "GET /api/docs/ HTTP/1.1" 404 7171
[2025-03-25 06:35:49] [WARNING] [django.request] Not Found: /api/
[2025-03-25 06:35:49] [WARNING] [django.server] "GET /api/ HTTP/1.1" 404 6970
[2025-03-25 06:35:54] [INFO] [django.server] "GET /api/usuarios/ HTTP/1.1" 200 1566
[2025-03-25 06:35:56] [WARNING] [django.request] Unprocessable Content: /api/usuarios/docs
[2025-03-25 06:35:56] [WARNING] [django.server] "GET /api/usuarios/docs HTTP/1.1" 422 148
[2025-03-25 06:36:06] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:36:07] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:36:32] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-25 06:36:32] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3311
[2025-03-25 06:36:40] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:36:41] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:36:45] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:36:47] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:37:09] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:37:10] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:37:11] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:37:12] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:37:15] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:37:16] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:37:36] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:37:37] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:37:40] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:37:41] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:38:15] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:38:15] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:38:20] [WARNING] [django.request] Unprocessable Content: /api/usuarios/docs
[2025-03-25 06:38:20] [WARNING] [django.server] "GET /api/usuarios/docs HTTP/1.1" 422 148
[2025-03-25 06:38:25] [WARNING] [django.request] Not Found: /
[2025-03-25 06:38:25] [WARNING] [django.server] "GET / HTTP/1.1" 404 5085
[2025-03-25 06:38:39] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 839
[2025-03-25 06:38:39] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3308
[2025-03-25 06:39:26] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:39:27] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:39:31] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:39:31] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:39:32] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:39:33] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:39:37] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:39:38] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:39:41] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:39:42] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:39:47] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:39:48] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:41:14] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:41:15] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:41:17] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:41:18] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:41:34] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:41:35] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:42:35] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:42:35] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:42:38] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:42:39] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:42:42] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 983
[2025-03-25 06:42:43] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3308
[2025-03-25 06:43:23] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:43:23] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:43:29] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:43:30] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:43:59] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:44:00] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:44:04] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 815
[2025-03-25 06:44:04] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3308
[2025-03-25 06:44:15] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:44:15] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:44:18] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:44:19] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:44:21] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 815
[2025-03-25 06:44:21] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3308
[2025-03-25 06:44:50] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3308
[2025-03-25 06:45:05] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:45:06] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:45:30] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:45:31] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:45:33] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:45:34] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:45:36] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 849
[2025-03-25 06:45:36] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3322
[2025-03-25 06:45:58] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:45:59] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:46:01] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:46:02] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:46:03] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 848
[2025-03-25 06:46:04] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3317
[2025-03-25 06:50:00] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:50:00] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:50:15] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:50:16] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:50:18] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:50:18] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:50:24] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:50:24] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:50:31] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:50:31] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:50:33] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:50:33] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:50:35] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 848
[2025-03-25 06:50:35] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3317
[2025-03-25 06:51:43] [INFO] [django.server] "GET /api/usuarios/ HTTP/1.1" 200 1566
[2025-03-25 06:52:32] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:52:33] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:52:53] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:52:53] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:52:57] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:52:57] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:52:59] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:53:00] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:53:04] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 848
[2025-03-25 06:53:04] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3317
[2025-03-25 06:53:19] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:53:20] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:53:21] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:53:22] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:53:38] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:53:39] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:53:51] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:53:52] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:54:04] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 06:54:05] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:54:07] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-25 06:54:08] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3311
[2025-03-25 06:54:28] [WARNING] [django.request] Not Found: /api/usuarios/152
[2025-03-25 06:54:28] [WARNING] [django.server] "GET /api/usuarios/152 HTTP/1.1" 404 60
[2025-03-25 06:55:08] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:55:08] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:55:10] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:55:11] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:55:12] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:55:13] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:55:16] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:55:17] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:55:37] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:55:38] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:55:41] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:55:42] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:55:43] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:55:44] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:55:45] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:55:46] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:56:43] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:56:43] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:56:51] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:56:52] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:56:54] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:56:55] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:57:14] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:57:14] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:57:23] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-25 06:57:23] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3448
[2025-03-25 06:57:36] [WARNING] [django.request] Not Found: /api/usuarios/111
[2025-03-25 06:57:36] [WARNING] [django.server] "GET /api/usuarios/111 HTTP/1.1" 404 60
[2025-03-25 06:57:42] [WARNING] [django.request] Not Found: /api/usuarios/111
[2025-03-25 06:57:42] [WARNING] [django.server] "GET /api/usuarios/111 HTTP/1.1" 404 60
[2025-03-25 06:58:15] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:58:17] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:58:19] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-25 06:58:19] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3441
[2025-03-25 06:58:20] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-25 06:58:20] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3441
[2025-03-25 06:58:38] [WARNING] [django.request] Not Found: /api/usuarios/1231231
[2025-03-25 06:58:38] [WARNING] [django.server] "GET /api/usuarios/1231231 HTTP/1.1" 404 46
[2025-03-25 06:59:31] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 06:59:33] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 06:59:40] [WARNING] [django.request] Not Found: /api/usuarios/115
[2025-03-25 06:59:40] [WARNING] [django.server] "GET /api/usuarios/115 HTTP/1.1" 404 46
[2025-03-25 06:59:41] [WARNING] [django.request] Not Found: /favicon.ico
[2025-03-25 06:59:41] [WARNING] [django.server] "GET /favicon.ico HTTP/1.1" 404 5136
[2025-03-25 06:59:43] [INFO] [django.server] "GET /api/usuarios/1 HTTP/1.1" 200 226
[2025-03-25 07:01:25] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 07:01:25] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:02:35] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 07:02:36] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:02:44] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-25 07:02:45] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3787
[2025-03-25 07:04:36] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 07:04:38] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:04:39] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-25 07:04:40] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 4825
[2025-03-25 07:05:30] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:05:31] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:05:37] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:05:39] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:05:41] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:05:42] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:05:44] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:05:44] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:05:56] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:05:56] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:06:01] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:06:01] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:06:02] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:06:03] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:06:05] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:06:06] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:06:12] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:06:13] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:06:14] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:06:14] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:06:18] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 818
[2025-03-25 07:06:19] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 4825
[2025-03-25 07:08:39] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 07:08:40] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:09:35] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 07:09:36] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:11:24] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:11:27] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 818
[2025-03-25 07:11:27] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 4825
[2025-03-25 07:12:44] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 818
[2025-03-25 07:12:44] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 4825
[2025-03-25 07:13:03] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:13:03] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:13:07] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:13:07] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:13:08] [INFO] [django.utils.autoreload] /home/vidal/programas_python/lojex/apps/api_rest/api.py changed, reloading.
[2025-03-25 07:13:09] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 07:13:17] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-25 07:13:17] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 4825
[2025-03-25 07:13:29] [INFO] [django.server] "GET /api/usuarios/ HTTP/1.1" 200 1566
[2025-03-25 07:13:47] [INFO] [django.server] "GET /api/usuarios/5 HTTP/1.1" 200 226
[2025-03-25 07:13:49] [WARNING] [django.request] Not Found: /api/usuarios/152
[2025-03-25 07:13:49] [WARNING] [django.server] "GET /api/usuarios/152 HTTP/1.1" 404 46
[2025-03-25 07:14:46] [INFO] [django.server] "GET /api/usuarios/2 HTTP/1.1" 200 216
[2025-03-25 13:00:12] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:02:07] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:02:07] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:04:12] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:04:13] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:04:17] [WARNING] [django.request] Not Found: /
[2025-03-25 13:04:17] [WARNING] [django.server] "GET / HTTP/1.1" 404 5085
[2025-03-25 13:04:19] [INFO] [django.server] "GET /login/ HTTP/1.1" 200 2857
[2025-03-25 13:04:19] [INFO] [django.server] "GET /static/assets/images/logos/logo.svg HTTP/1.1" 200 8334
[2025-03-25 13:04:19] [INFO] [django.server] "GET /static/assets/libs/jquery/dist/jquery.min.js HTTP/1.1" 200 88151
[2025-03-25 13:04:19] [INFO] [django.server] "GET /static/assets/css/styles.min.css HTTP/1.1" 200 442049
[2025-03-25 13:04:19] [INFO] [django.server] "GET /static/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js HTTP/1.1" 200 80599
[2025-03-25 13:04:19] [INFO] [django.server] "GET /static/assets/libs/simplebar/dist/simplebar.css HTTP/1.1" 200 3890
[2025-03-25 13:04:19] [INFO] [django.server] "GET /static/assets/css/icons/tabler-icons/tabler-icons.css HTTP/1.1" 200 146896
[2025-03-25 13:04:19] [INFO] [django.server] "GET /static/assets/libs/jquery/dist/jquery.min.js HTTP/1.1" 200 88151
[2025-03-25 13:04:19] [INFO] [django.server] "GET /static/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js HTTP/1.1" 200 80599
[2025-03-25 13:04:19] [INFO] [django.server] "GET /api/docs HTTP/1.1" 200 986
[2025-03-25 13:04:20] [INFO] [django.server] "GET /api/openapi.json HTTP/1.1" 200 3787
[2025-03-25 13:04:24] [INFO] [django.server] "GET /api/usuarios/ HTTP/1.1" 200 1566
[2025-03-25 13:04:35] [INFO] [django.server] "GET /api/usuarios/1 HTTP/1.1" 200 226
[2025-03-25 13:04:49] [INFO] [django.server] "POST /api/usuarios/ HTTP/1.1" 201 199
[2025-03-25 13:04:57] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-25 13:04:57] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
[2025-03-25 13:04:59] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-25 13:04:59] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
[2025-03-25 13:05:00] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-25 13:05:00] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
[2025-03-25 13:06:38] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:06:39] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:06:50] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:06:50] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:07:07] [WARNING] [django.request] Unprocessable Content: /api/usuarios/
[2025-03-25 13:07:07] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 422 218
[2025-03-25 13:08:01] [INFO] [django.server] "POST /api/usuarios/ HTTP/1.1" 201 214
[2025-03-25 13:11:30] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:11:31] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:11:58] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-25 13:11:58] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 61
[2025-03-25 13:12:17] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:12:18] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:12:20] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:12:21] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:12:22] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:12:22] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:13:25] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:13:26] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:13:28] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-25 13:13:28] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
[2025-03-25 13:13:33] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-25 13:13:33] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
[2025-03-25 13:13:47] [WARNING] [django.request] Unprocessable Content: /api/usuarios/
[2025-03-25 13:13:47] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 422 218
[2025-03-25 13:14:41] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:14:42] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:14:46] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:14:47] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:14:58] [WARNING] [django.request] Unprocessable Content: /api/usuarios/
[2025-03-25 13:14:58] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 422 218
[2025-03-25 13:15:00] [WARNING] [django.request] Unprocessable Content: /api/usuarios/
[2025-03-25 13:15:00] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 422 218
[2025-03-25 13:15:05] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:15:05] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:15:09] [WARNING] [django.request] Unprocessable Content: /api/usuarios/
[2025-03-25 13:15:09] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 422 218
[2025-03-25 13:16:06] [INFO] [django.server] "GET /api/usuarios/ HTTP/1.1" 200 1983
[2025-03-25 13:16:14] [WARNING] [django.request] Unprocessable Content: /api/usuarios/
[2025-03-25 13:16:14] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 422 218
[2025-03-25 13:16:47] [INFO] [django.server] "DELETE /api/usuarios/9 HTTP/1.1" 200 17
[2025-03-25 13:16:50] [WARNING] [django.request] Not Found: /api/usuarios/9
[2025-03-25 13:16:50] [WARNING] [django.server] "DELETE /api/usuarios/9 HTTP/1.1" 404 46
[2025-03-25 13:16:53] [WARNING] [django.request] Not Found: /api/usuarios/9
[2025-03-25 13:16:53] [WARNING] [django.server] "DELETE /api/usuarios/9 HTTP/1.1" 404 46
[2025-03-25 13:16:59] [WARNING] [django.request] Unprocessable Content: /api/usuarios/
[2025-03-25 13:16:59] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 422 218
[2025-03-25 13:17:07] [INFO] [django.server] "POST /api/usuarios/ HTTP/1.1" 201 215
[2025-03-25 13:17:17] [INFO] [django.server] "DELETE /api/usuarios/10 HTTP/1.1" 200 17
[2025-03-25 13:17:58] [WARNING] [django.request] Bad Request: /api/usuarios/7
[2025-03-25 13:17:58] [WARNING] [django.server] "PUT /api/usuarios/7 HTTP/1.1" 400 113
[2025-03-25 13:18:16] [ERROR] [django] Schema for status 500 is not set in response dict_keys([200, 404])
Traceback (most recent call last):
  File "/home/vidal/Programas/lojex/.venv/lib/python3.13/site-packages/ninja/operation.py", line 134, in run
    return self._result_to_response(request, result, temporal_response)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vidal/Programas/lojex/.venv/lib/python3.13/site-packages/ninja/operation.py", line 262, in _result_to_response
    raise ConfigError(
    ...<2 lines>...
    )
ninja.errors.ConfigError: Schema for status 500 is not set in response dict_keys([200, 404])
[2025-03-25 13:18:16] [ERROR] [django.request] Internal Server Error: /api/usuarios/7
[2025-03-25 13:18:16] [ERROR] [django.server] "PUT /api/usuarios/7 HTTP/1.1" 500 555
[2025-03-25 13:20:07] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:20:08] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:20:24] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:20:24] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:21:38] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:21:38] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:21:40] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/routers.py changed, reloading.
[2025-03-25 13:21:40] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:21:55] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:21:55] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:21:57] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:21:58] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:22:05] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:22:05] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:22:07] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:22:07] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:22:09] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:22:10] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:22:11] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:22:12] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:22:24] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:22:25] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:22:29] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:22:30] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:22:42] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:22:42] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:22:44] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:22:44] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:22:50] [INFO] [django.server] "PUT /api/usuarios/7 HTTP/1.1" 200 210
[2025-03-25 13:22:56] [INFO] [django.server] "PUT /api/usuarios/7 HTTP/1.1" 200 210
[2025-03-25 13:23:03] [WARNING] [django.request] Bad Request: /api/usuarios/7
[2025-03-25 13:23:03] [WARNING] [django.server] "PUT /api/usuarios/7 HTTP/1.1" 400 113
[2025-03-25 13:23:10] [INFO] [django.server] "PUT /api/usuarios/7 HTTP/1.1" 200 210
[2025-03-25 13:23:21] [INFO] [django.server] "PUT /api/usuarios/7 HTTP/1.1" 200 210
[2025-03-25 13:23:28] [INFO] [django.server] "PUT /api/usuarios/7 HTTP/1.1" 200 207
[2025-03-25 13:23:44] [WARNING] [django.request] Unprocessable Content: /api/usuarios/7
[2025-03-25 13:23:44] [WARNING] [django.server] "PUT /api/usuarios/7 HTTP/1.1" 422 215
[2025-03-25 13:39:33] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:39:34] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:39:36] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:39:37] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:39:43] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:39:44] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:40:01] [INFO] [django.utils.autoreload] /home/vidal/Programas/lojex/apps/usuarios/schemas.py changed, reloading.
[2025-03-25 13:40:01] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-03-25 13:41:16] [INFO] [django.server] "POST /api/usuarios/ HTTP/1.1" 201 215
[2025-03-25 13:41:19] [WARNING] [django.request] Bad Request: /api/usuarios/
[2025-03-25 13:41:19] [WARNING] [django.server] "POST /api/usuarios/ HTTP/1.1" 400 57
